### ISSUE TITLE
Desktop build breaks on shared ComputeInputs changes (collapsed_tickets missing) — CI gap

### ISSUE THREAD

**Issue by antoinetoussaint-byte** [AntoineToussaint/lazybox#1207]
The desktop app (`apps/desktop/src-tauri`) failed to compile after #1189 (collapsible ticket hierarchy) added `collapsed_tickets: &HashSet<TaskId>` to the shared `ComputeInputs` — the desktop's `inbox::compute_visible(ComputeInputs { … })` call site wasn't updated:
```
error[E0063]: missing field `collapsed_tickets` in initializer of `ComputeInputs<'_>`
  --> apps/desktop/src-tauri/src/main.rs:295
```

## Immediate fix (done)
Added `collapsed_tickets: &std::collections::HashSet::new()` to the desktop call site, matching the other "no X UI on the desktop yet" empty defaults (`collapsed_spaces`, `focused_workspaces`, `spaces`, `pinned_repos`).

## Systemic gap (the real issue)
The desktop is a **separate Cargo workspace**, so `cargo build/clippy` from the root doesn't touch it and the main CI doesn't gate it. Any change to a **shared type** (`ComputeInputs`, IPC DTOs, inbox builder) can break the desktop **silently** — this is at least the second time (cf. the desktop contract fixture drift, and desktop fmt/clippy not in pre-commit).

Fix directions:
- Add the desktop crate to CI so a shared-type change that breaks it **fails the PR** (a `cargo check` on `apps/desktop/src-tauri` in the desktop workflow, gating merges — not just the desktop-MVP job).
- Or make `ComputeInputs` additions harder to miss (e.g. a `#[non_exhaustive]` + builder with defaults, so a new field doesn't force every call site to change and can't silently break an out-of-workspace caller).

Related: desktop contract fixture regen chore; desktop fmt/clippy not in pre-commit.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
